name: Run Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Modules
        run: npm ci 
        
      - name: Run Cypress Tests
        uses: Cypress-io/github-action@v3
        with:
          browser: chrome
          headless: false
          start: npm start

      - name: Generate HTML Report
        if: success()
        run: npm run generate:report
